name: garkran_reading_app
description: Aplicativo de leitura de livros
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/confissoes.png
    - assets/sumula.png
    - assets/metafisica.png
    - assets/logo.png
    - assets/branding.png
